package com.kycnetwork.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class BankAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBankAllPropertiesEquals(Bank expected, Bank actual) {
        assertBankAutoGeneratedPropertiesEquals(expected, actual);
        assertBankAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBankAllUpdatablePropertiesEquals(Bank expected, Bank actual) {
        assertBankUpdatableFieldsEquals(expected, actual);
        assertBankUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBankAutoGeneratedPropertiesEquals(Bank expected, Bank actual) {
        assertThat(actual)
            .as("Verify Bank auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBankUpdatableFieldsEquals(Bank expected, Bank actual) {
        assertThat(actual)
            .as("Verify Bank relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getBicCode()).as("check bicCode").isEqualTo(expected.getBicCode()))
            .satisfies(a -> assertThat(a.getCountry()).as("check country").isEqualTo(expected.getCountry()))
            .satisfies(a -> assertThat(a.getIsActive()).as("check isActive").isEqualTo(expected.getIsActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBankUpdatableRelationshipsEquals(Bank expected, Bank actual) {
        // empty method
    }
}
